### PR TITLE
add approximate number of messages

### PR DESCRIPTION
**Pull request by nxvl**

### CODE REVIEW

**Comment by shosti** [comment]
Does this do anything?

**Comment by usami** [comment]
In my understanding, it's needed for auto-scaling, right?

**Comment by nxvl** [comment]
Tala uses SimpleSQS and to get the Approximate number of messages for hirefire configuration would be an horrible hack, this makes it simpler by adding the method to simplesqs

**Comment by shosti** [comment]
Oh, missed that this is on simple_sqs and not tala.

**Pull request merged**
